# Generated by Django 3.1.3 on 2020-12-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_experience_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Affiliation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='ContactPerson',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='OfficeHour',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Region',
            field=models.CharField(blank=True, choices=[('Addis Ababa', 'Addis Ababa'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('Dire Dawa', 'Dire Dawa'), ('Gambela', 'Gambela'), ('Harari', 'Harari'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Tigray', 'Tigray')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Telephone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
