# Generated by Django 3.1.3 on 2020-12-05 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_remove_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='Фото',
        ),
    ]
